#!/bin/sh

set -e
echo
echo "PRE-COMMIT  CHECKS"
echo "----------------"

# see if the user is trying to commit to the master branch
if [ "$branch" = "master" ]; then
	read -p "  You are about to commit to the master branch, are you sure? [y|n] " -n 1 -r < /dev/tty
	echo
	if echo $REPLY | grep -E '^[Yy]$' > /dev/null
	then
		exit 0 # commit will execute
	fi
	exit 1 # commit will not execute
fi


git push heroku master

echo "  Commit successful..."
